kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: varlog
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: varvcap
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: varlibdockercontainers
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: libsystemddir
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: vsphere-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
